version: "3.8"
name: monitorss-prod
services:
  bot-presence-service:
    extends:
      file: ./docker-compose.base.yml
      service: bot-presence-service
    build:
      context: services/bot-presence
      dockerfile: Dockerfile
      target: prod
    command: [ "node", "dist/main.js" ]

  feed-requests-redis-cache:
    extends:
      file: ./docker-compose.base.yml
      service: feed-requests-redis-cache

  rabbitmq-broker:
    extends:
      file: ./docker-compose.base.yml
      service: rabbitmq-broker

  mongo:
    extends:
      file: ./docker-compose.base.yml
      service: mongo

  feed-requests-postgres-db:
    extends:
      file: ./docker-compose.base.yml
      service: feed-requests-postgres-db

  user-feeds-postgres-db:
    extends:
      file: ./docker-compose.base.yml
      service: user-feeds-postgres-db

  discord-rest-listener-service:
    extends:
      file: ./docker-compose.base.yml
      service: discord-rest-listener-service
    build:
      context: services/discord-rest-listener
      dockerfile: Dockerfile
      target: prod
    command: [ "node", "build/app.js" ]

  feed-requests-service:
    extends:
      file: ./docker-compose.base.yml
      service: feed-requests-service
    build:
      context: services/feed-requests
      dockerfile: Dockerfile
      target: prod
    command: [ "node", "dist/main.js" ]
    environment:
      - NODE_ENV=production

  feed-requests-api:
    extends:
      file: ./docker-compose.base.yml
      service: feed-requests-api
    build:
      context: services/feed-requests
      dockerfile: Dockerfile
      target: prod
    command: [ "node", "dist/main.js" ]
    environment:
      - NODE_ENV=production

  feed-requests-postgres-migration:
    extends:
      file: ./docker-compose.base.yml
      service: feed-requests-postgres-migration
    build:
      context: services/feed-requests
      dockerfile: Dockerfile
      target: build
    command: "npm run migration:local:up"

  user-feeds-service:
    extends:
      file: ./docker-compose.base.yml
      service: user-feeds-service
    build:
      context: services/user-feeds
      dockerfile: Dockerfile
      target: prod
    command: [ "node", "dist/main.js" ]

  user-feeds-postgres-migration:
    extends:
      file: ./docker-compose.base.yml
      service: user-feeds-postgres-migration

  legacy-feed-bulk-converter-service:
    extends:
      file: ./docker-compose.base.yml
      service: legacy-feed-bulk-converter-service
    build:
      context: services/backend-api
      dockerfile: dockerfiles/legacy-feed-bulk-converter/Dockerfile
      target: prod
    command: [ "node", "dist/scripts/legacy-feed-bulk-converter.js" ]

  schedule-emitter-service:
    extends:
      file: ./docker-compose.base.yml
      service: schedule-emitter-service
    build:
      context: services/backend-api
      dockerfile: dockerfiles/schedule-emitter/Dockerfile
      target: prod
    command: [ "node", "dist/scripts/schedule-emitter.js" ]

  monolith:
    build:
      context: services/backend-api
      dockerfile: dockerfiles/web/mixed.Dockerfile
      target: prod
    restart: on-failure:3
    depends_on:
      - mongo
      - user-feeds-service
      - feed-requests-service
    ports:
      - "6005:6005"
    environment:
      - BACKEND_API_NODE_ENV=local
      - BACKEND_API_PORT=6005
      - BACKEND_API_DEFAULT_MAX_FEEDS=999999
      - BACKEND_API_USER_FEEDS_API_HOST=http://user-feeds-service:5000
      - BACKEND_API_FEED_REQUESTS_API_HOST=http://feed-requests-api:5000
      - BACKEND_API_FEED_USER_AGENT=MonitoRSS
      - BACKEND_API_RABBITMQ_BROKER_URL=amqp://guest:guest@rabbitmq-broker:5672/
      - BACKEND_API_USER_FEEDS_API_KEY=user-feeds-api-key
      - BACKEND_API_FEED_REQUESTS_API_KEY=feed-requests-api-key
      - LOG_LEVEL=info
    command: [ "node", "dist/main.js" ]
    networks:
      - monitorss-default

volumes:
  mongodb-data:
    driver: local
  feed-requests-postgres-data:
    driver: local
  user-feeds-postgres-data:
    driver: local
  feed-requests-redis-data:
    driver: local

networks:
  monitorss-default:
    driver: bridge