version: "3.8"
services:
  mrss-mongo:
    container_name: mrss-mongodb-container
    restart: on-failure:5
    command: mongod --port 27017
    logging:
      driver: none
    image: mongo:latest
    volumes:
      - 'db-data:/data/db'
  mrss-web:
    container_name: mrss-web-container
    build: .
    restart: on-failure:3
    depends_on:
      - mrss-mongo
    ports:
      - "6005:6005"
    environment:
      - NODE_ENV=local
      - BACKEND_API_MONGODB_URI=mongodb://mrss-mongo:27017/rss

volumes:
  db-data:
